# Metadata table

metadata <- data.frame(
  dataset = c("2006_RNF43",
              "2006_RNF122",
              "2006_RNFT2",
              "2434_2660",
              "2999",
              "3019",
              "3676",
              "4310_CK1s",
              "4310_FZDs",
              "4453_DDA",
              "4453_DIA"),
  acquisition = c("DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DDA",
                  "DIA"),
  responsible_person = c("Tomek",
                         "Tomek",
                         "Tomek",
                         "Tomek",
                         "Marek",
                         "Tomek/PetaP",
                         "Vendy",
                         "Tomas",
                         "Tomas",
                         "Tomas",
                         "Tomas"),
  PRIDE = c("PXD020478",
            "-",
            "-",
            "PXD039259",
            "PXD034237, PXD033548",
            "-",
            "PXD041751",
            "-",
            "-",
            "-",
            "-"),
  analysis = c("KNIME",
               "KNIME",
               "KNIME",
               "DEP",
               "KNIME",
               "DEP",
               "R",
               "DEP",
               "DEP",
               "DEP",
               "KNIME"),
  note = c("",
           "qualitative hits reported separately, check the source file on server",
           "",
           "",
           "log2, norm; check source for imp",
           "",
           "no stats done",
           "batch correction",
           "batch correction",
           "interaction limma",
           ""),
  type = c("default",
           "default",
           "default",
           "default",
           "default",
           "default",
           #"multipleContrasts",
           #"multipleContrasts",
           "noStats",
           "default",
           "default",
           "default",
           "default"
           # "multipleContrasts",
           # "multipleContrasts",
           # "multipleContrasts",
           #"multipleContrasts"))
  ))

str(metadata)

# Write the metadata
write.csv(metadata, here('metadata.csv'))
